import "./globals.css";
import Header from "@components/Header/Header";
import Footer from "@components/Footer/Footer";

export const metadata = {
  title: "SUSG Academic Databank",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header></Header>
        <div
          style={{
            display: "flex",
            justifyContent: "center",
            alignItems: "center",
            height: "50vh",
          }}
        >
          {children}
        </div>
        <Footer></Footer>
      </body>
    </html>
  );
}
