import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../components/Header/Header";
import CreateButton from "@/components/create-button";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "SUSG Academic Databank",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header></Header>
        <CreateButton></CreateButton>
        {children}
      </body>
    </html>
  );
}
